title: Bandas de 1 Álbum
subtitle: Eternizando One Album Wonders
email: bandasde1album@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  O Bandas de 1 Álbum tem por propósito eternizar as 'One Album Wonders', aquelas bandas que lançaram apenas um disco de estúdio na carreira.
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://bandas1album.com.br' # the base hostname & protocol for your site, e.g. http://example.com
shareImage: '/assets/img/share.png'
twitter_username: bandas1album
instagram_username: bandas1album
facebook_username: bandas1album
permalink: /:title

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
  layout: category
  permalinks:
    category: '/genero/:name/'

sass:
  load_paths:
    - src/scss
    - node_modules

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - src/
  - LICENSE
